[project]
name = "rabota"
version = "0.1.0"
description = "Практическая работа №1"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "prompt>=0.4.1",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages]
find = {}

[dependency-groups]
dev = [
    "ruff>=0.15.2",
]

[project.scripts]
VD-games = "VD_games.scripts.games:game_function"
VD-even = "VD_games.scripts.VD_even:play_game"
[tool.ruff]
line-length = 79

[tool.ruff.lint]
extend-select = [
    "I",
    "D",
    "UP",
    "C4",
    "BLE",
    "RUF",
]
ignore = ["D100", "D101", "D102", "D103", "D104", "D105", "D106", "D107", "D200", "D205", "D212"]

[tool.ruff.lint.pydocstyle]
convention = "google"

