[project]
name = "vd-games"
version = "1.0.0"
description = "VD Games: even, calculator, gcd"
authors = [{name = "Khava Gazaloeva", email = "isip_h.gazaloeva@mpt.ru"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["prompt>=0.4.1"]

[project.scripts]
VD-games = "cli:main"
VD-even = "scripts.VD_even:main"
VD-calc = "scripts.VD_calc:main"
VD-gcd = "scripts.VD_gcd:main"
VD-progression = "scripts.VD_progression:main"
VD-prime = "scripts.VD_prime:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["games*", "scripts*"]

[dependency-groups]
dev = [
    "ruff>=0.15.9",
]
